name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Archive artifacts
        run: |
          tar -czvf django-app.tar.gz .
        
      - name: Upload artifact to S3
        run: |
          aws s3 cp django-app.tar.gz s3://silassessmentbucket/
          

    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to aws instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu
            sudo apt-get update
            sudo apt-get install -y python3-pip
            aws s3 cp s3://silassessmentbucket/django-app.tar.gz .
            tar -xzvf django-app.tar.gz
            cd django-app
            pip3 install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
